# Generated by Django 3.2.14 on 2022-09-27 23:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listing_created_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='created_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 28, 1, 34, 33, 20388)),
        ),
    ]
