# Generated by Django 3.2.14 on 2022-11-15 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_listing_created_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='created_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 13, 44, 6, 12682)),
        ),
    ]
