# Generated by Django 4.1.4 on 2022-12-10 05:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_listing_created_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 7, 1, 1, 637580)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='created_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 7, 1, 1, 636580)),
        ),
    ]
